# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SMG_ZahlenAufgabe GitHubAction

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Clean Workspace 
      working-directory: SMG_ZahlenAufgabe
      run: mvn clean
    - name: Install Dependencies
      working-directory: SMG_ZahlenAufgabe
      run: mvn install 
    - name: Compile
      working-directory: SMG_ZahlenAufgabe
      run: mvn compile 
    - name: Generate Documentation
      working-directory: SMG_ZahlenAufgabe
      run: mvn doxygen:generate      
           
           
